### PR TITLE
Use appropriate target environement for eval, assignments, and dep-checks

### LINKED ISSUE #20: Using stash() inside a function causes an error, "object 'yyy' not found"
I love `mustashe`, its `here()` awareness fits very neatly with my workflow.

However, now I want to use `stash()` inside a function, but code that works in the global environment does not work inside a function. The issue probably has to do with the environment in which the stash code is evaluated, but since I don't see any parameters to change that, I'm filing this as an issue. Below is a full `reprex` illustrating the problem.

A few points:

* Renaming from `xxx` to `yyy` is only done to not get leakage of variable names across scope.
* In my actual use case, I want to set `yyy` based on some logic inside the function and use `depends_on` to trigger a restash if the contents of `yyy` have changed. This results in a different error, but with the same symptoms (works in global environment but not inside a function.
* I'm including in the reprex both versions, with and without `depends_on`.

``` r
library(mustashe)
## clear_stash() # Commented in posted version to protect from inadvertent clearing
#> Clearing stash.
set.seed(42)

xxx <- letters
stash("result_xxx", {sample(xxx,1)}, functional=TRUE ) |> print()
#> Stashing object.
#> [1] "q"

funky <- function() {
  yyy <- letters
  stash("result_yyy", {sample(yyy,1)}, functional=TRUE ) |> print()
}
funky()
#> Stashing object.
#> Error in sample(yyy, 1): object 'yyy' not found

xxxx <- letters
stash("result_xxxx", {sample(xxxx,1)}, functional=TRUE, depends_on="xxxx" ) |> print()
#> Stashing object.
#> [1] "e"

funky2 <- function() {
  yyyy <- letters
  stash("result_yyyy", {sample(yyyy,1)}, functional=TRUE, depends_on="yyyy" ) |> print()
}
funky2()
#> Error in make_hash(depends_on, .TargetEnv): Some dependencies are missing from the environment.
```

<sup>Created on 2022-03-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by torfason**
This PR updates the `stash()` function and underlying private functions to keep track of the appropriate target environment (`target_env`) for evaluating the stashed expression, for assigning the result, and for looking for dependencies.

With this change, `stash()` is no longer dependent on the relevant variables being present in the global environment (`.GlobalEnv`), which makes it easier to use inside other functions.

The PR also adds tests related to this new functionality, and updates some existing tests (which no longer need to make assignments to `.GlobalEnv`).

This PR is proposed as a fix for issue #20.

### CODE REVIEW

File: R/stash.R [hunk 1]
```diff
@@ -38,7 +38,10 @@ stash <- function(var, code, depends_on = NULL, functional = FALSE, verbose = TR
   if (is.null(var)) stop("`var` cannot be NULL")
   if (formatted_code == "NULL") stop("`code` cannot be NULL")
 
-  new_hash_tbl <- make_hash_table(formatted_code, depends_on)
+  # The environment where all code is evaluated and variables assigned.
+  target_env <- parent.frame()
```
Comment (jhrcook) [inline R/stash.R:43]: Great idea just getting the parent frame at the beginning. Much easier solution than trying to dig through layers of function calls later.

**Review by jhrcook — COMMENTED** [review]
The change to `stash()` is great and a very simple fix to what could have been a headache. I want to add a few things to the new tests and play around with this dev version of 'mustashe' locally, but otherwise, this looks good to merge.
